# Generated by Django 5.0.1 on 2024-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_bookprofile_remove_userprofile_id_userprofile_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userID',
            new_name='user_id',
        ),
    ]
